### ISSUE TITLE
How this tool can be used

### ISSUE THREAD

**Issue by eliassal** [flokli/vigor-exporter#3]
Hi flokli, can you please let me know how this can be used? I have a Draytek vigor 2926 and would like to know if it is possible to use your exporter.
Thanks in advance

**Comment by flokli** [comment]
Oops sorry, it seems I messed up my GitHub notifications :-/

I also received an email about this, replied and pushed https://github.com/flokli/vigor-exporter/commit/593a1d6619d1104c4f13debf47a192d1db373a3a, so this can probably be closed.

**Comment by eliassal** [comment]
OK, thanks, I tried, inside my IDE, Visual studio code, I run and it seems to me that there is no error as you can notice in the snapshot but when I try to access, I get "Unable to connect.
I checked if an application is listening on port 9103 with
```
netstat -aon
or
netstat -aof | findstr  :9103
```
I dont see any app listening on port 9103

Should we see an output (information.....) when we run the exporter or just nothing?

![VigorExporter](https://user-images.githubusercontent.com/8447864/154049653-c7d61641-f11d-4b4f-b7de-4dbfa95b33bb.jpg)

**Comment by eliassal** [comment]
Quick question, does it use SNMP protocol? if yes which version? and how can we debug the tool to see if it is connecting or not, thanks

**Comment by flokli** [comment]
No, this doesn't use snmp, but scrapes the web interface - check `vigor/{status,login}.go`.

Make sure to call this with `vigor-node-exporter -host hostnameOrIp -username admin -password yourpassword`.

Error handling isn't great right now, but might be improved by https://github.com/flokli/vigor-exporter/pull/2.

**Comment by eliassal** [comment]
I am putting details in main.go
```
var username = flag.String("username", "mysuer", "username to authenticate to the Vigor")
var password = flag.String("password", "mypassword", "password to authenticate to the Vigor")
var host = flag.String("host", "myIP", "hostname/ip the Vigor is reachable on")
```

Should I put those on the command line?

Why do use "vigor-node-exporter", after compilation the executable is "vigor-exporter.exe" !!!!

**Comment by flokli** [comment]
> I am putting details in main.go

You shouldn't need to edit the source code. Just compile it for your platform, and invoke it with the right parameters

> Why do use "vigor-node-exporter", after compilation the executable is "vigor-exporter.exe" !!!!

This only seems to be the case on windows, not WSL, not linux and not macos.

**Comment by fleaz** [comment]
> Why do use "vigor-node-exporter", after compilation the executable is "vigor-exporter.exe" !!!!

The tool was called `vigor-node-exporter` before the repository was migrated to flokli (see f70b5ad8cbd7aa4625d38b79990e32b7d4f21b26). He probably just had the old name in mind. Nowadays it's called `vigor-exporter` on all platforms :)

**Comment by eliassal** [comment]
fleaz, OK, but I have the impression, in spite of the fact that there are no errors when I run 
 .\vigor-exporter.exe -host "vigorrouterIP" -username "admin" -password "rightpassword"
I get a blinking vertical line forever and cant access

http://localhost:9103/metrics
http://mypc:9103/metrics 
http://127.0.0.1:9103/metrics

I get "Unable to connect as I indicated earlier, nothing is listening on port 9103. Is there anyway to activate a log to see what is happenin? I have never used GO language

**Comment by fleaz** [comment]
Could you please pull the repository and build the code again? My PR from yesterday adding some logging so we maybe should see what is happening.

Also, the main http handler which accepts your concoction is started *after* the connection to the modem is established. So maybe the connection can't be established because the IP is wrong or not routed or stuck in a firewall? Can you open the IP you use for the exporter in your browser on the same machine and get the web interface of the Vigor?

**Comment by eliassal** [comment]
Thannks delix, yes there was an error from my side not indicating the right port as I use https and not http. Now I can access the /metrics page. So tell me can I use the https instead of HTTP?
Also, can you please tell which metrics are related to traffic in/out?
Thanks

**Comment by fleaz** [comment]
Nice to hear that it's working now :)

From what I know, Prometheus exporter never handle TLS on their own because usually they are either run inside their own network when used in e.g. a datacenter or via a VPN when run over the internet.

When you wan't to access your exporter via HTTPS the recommended way is to put a reverse proxy in front like e.g. Caddy,traefik or nginx.

> Also, can you please tell which metrics are related to traffic in/out? 

Depending on the mode you are using, the Vigor is not aware of the actual amount of traffic passing through. E.g. when you use "PPPoE passthrough" to a router behind it. 
Can't tell if you actually get any traffic information when the Vigor is the PPPoE client because I never used it this way.

**Comment by eliassal** [comment]
I use Cacti, which uses snmp, I get LAN and WAN Traffic

> LAN

![DrayTek-TrafficLan](https://user-images.githubusercontent.com/8447864/154337668-8db44519-275f-4d87-aa59-d6898ce9301c.jpg)

> WAN

![DrayTek-TrafficWan](https://user-images.githubusercontent.com/8447864/154337736-8f6ccbe6-ddb5-4a91-92d0-783eeb443713.jpg)

**Comment by fleaz** [comment]
I just skimmed the code and from what I can tell, this exporter only exports metrics about  the status/quality of the DSL connection and no traffic values. SNMP indeed does export more/all values

**Comment by eliassal** [comment]
OK, thanks. Did you create any Grafana Dashboard for the Draytek?
